name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH agent
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Copy files via SSH
        run: scp -r ./* root@172.93.102.38:/root/robloxhackers.lol

      - name: Build and restart the application
        run: |
          ssh root@172.93.102.38 << 'EOF'
            cd /root/robloxhackers.lol
            npm install
            npm run build
            pm2 restart robloxhackers.lol || pm2 start npm --name "robloxhackers.lol" -- start
          EOF
