name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH agent
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add server to known_hosts
        run: |
          mkdir -p ~/.ssh
          echo "198.186.130.123 ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC6Pyk2yLtjLUfd9Yz0hIzWDzz7H5uqRycxMbIEr+NHNJe6q5KkP5PLfnkVr1S4GAbRB2BKfTTcoejzUasyfPxZ7iVVsRI32LlP0r20it5uiBa4PxDpsNRA0NprfRMjStcg2dGye2wST3G43QWrOOu8XJrau4vHYoWl8c2ePzUbtiTqyX71knfU8Y4U9nNzQtAAV2CNGGE6XSrF2iOVuSUwQ5s5mUCzykjNXgXezny8uEl/Hn8FMQUajYk0Ceja2sYZ5lJwPmrKdU0EiVvMfu7gUhdLd64yNBTqSX2dnTeYdvidKJp933qI1z05Ffe8N3sZyI5+d80xdsgFK8wbxrpjUvYXaMCGUswcHTMZiz9A3QlLdQEjgNhfA/qJsKY3SGz5GiLSex6v27sQwQwiq0rZdOvFyC32sGCeWVprD1eCnSw/VgjgNWVEdsvB6SqRCxwtvyrKzQYumsEqsZtVbitTx4OTY4PvCcbj0Ho69aE33awqkKkimx+9fnhrrz0jPMs=" >> ~/.ssh/known_hosts
          echo "198.186.130.123 ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBHm1wW49MguO386pqRGrM2RUk+vBXWSB4+ubC1UErQp1cZrQW7PlOpyktJ8lt61H/3bKGTwONSvE927OC2sqJ9I=" >> ~/.ssh/known_hosts
          echo "198.186.130.123 ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAUVc6NyQcXXOGPWegLP0mEfKqpdtjIX6s8/4yN5aflx" >> ~/.ssh/known_hosts

      - name: Remove old files
        run: ssh root@198.186.130.123 'rm -rf /root/robloxhackers.lol/*'

      - name: Copy files via SSH
        run: scp -r ./* root@198.186.130.123:/root/robloxhackers.lol

      - name: Build and restart the application
        run: |
          ssh root@198.186.130.123 << 'EOF'
            # Add NVM paths to the current session
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
            [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
            
            # Add paths for npm and pm2 explicitly
            export PATH="/root/.nvm/versions/node/v22.6.0/bin:$PATH"

            cd /root/robloxhackers.lol
            npm install
            npm run build
            echo 'npx next start -H 0.0.0.0 -p 80' > start.sh
            chmod +x start.sh
            pm2 stop robloxhackers.lol || true
            pm2 delete robloxhackers.lol || true
            pm2 start ./start.sh --name "robloxhackers.lol"
            pm2 save
          EOF
